// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcKi1rax8b0P9JdwDzqiq6UZgKCO0y95Y',
    appId: '1:777042848001:web:17455a17e21d4651cb9300',
    messagingSenderId: '777042848001',
    projectId: 'decepticon-111b3',
    authDomain: 'decepticon-111b3.firebaseapp.com',
    storageBucket: 'decepticon-111b3.firebasestorage.app',
    measurementId: 'G-R2WSBBLYP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOFxk-Cdt3sUncDgB_SNhhlRaoLxKhRfM',
    appId: '1:777042848001:android:51aca495584d9dddcb9300',
    messagingSenderId: '777042848001',
    projectId: 'decepticon-111b3',
    storageBucket: 'decepticon-111b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZHvyjhPeCcmA-0JtkGS8HmholZnlEVAo',
    appId: '1:777042848001:ios:4fc350872d2c0167cb9300',
    messagingSenderId: '777042848001',
    projectId: 'decepticon-111b3',
    storageBucket: 'decepticon-111b3.firebasestorage.app',
    iosBundleId: 'com.example.k',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZHvyjhPeCcmA-0JtkGS8HmholZnlEVAo',
    appId: '1:777042848001:ios:4fc350872d2c0167cb9300',
    messagingSenderId: '777042848001',
    projectId: 'decepticon-111b3',
    storageBucket: 'decepticon-111b3.firebasestorage.app',
    iosBundleId: 'com.example.k',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcKi1rax8b0P9JdwDzqiq6UZgKCO0y95Y',
    appId: '1:777042848001:web:7ffaa3701e2a2872cb9300',
    messagingSenderId: '777042848001',
    projectId: 'decepticon-111b3',
    authDomain: 'decepticon-111b3.firebaseapp.com',
    storageBucket: 'decepticon-111b3.firebasestorage.app',
    measurementId: 'G-SLX4CE8ZLK',
  );
}
